"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import {
  BookOpen,
  Columns,
  Lightbulb,
  Link as LinkIcon,
  HelpCircle,
  ChevronDown,
  ChevronUp,
  Sparkles,
} from "lucide-react";
import type { ComponentType } from "react";

interface CardContent {
  text?: string;
  summary?: string;
  [key: string]: unknown;
}

interface CardData {
  id: string;
  card_type: string;
  title: string;
  content: string | CardContent | null | undefined;
  display_order: number;
}

interface CardProps {
  card: CardData;
}

interface CardTypeStyle {
  bg: string;
  border: string;
  iconBg: string;
  iconColor: string;
  icon: ComponentType<{ size?: number; className?: string }>;
  label: string;
}

const PREVIEW_CHAR_LIMIT = 200;

const cardTypeConfig: Record<string, CardTypeStyle> = {
  summary: {
    bg: "bg-blue-50/60",
    border: "border-blue-200",
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
    icon: BookOpen,
    label: "Summary",
  },
  comparison: {
    bg: "bg-orange-50/60",
    border: "border-orange-200",
    iconBg: "bg-orange-100",
    iconColor: "text-orange-600",
    icon: Columns,
    label: "Comparison",
  },
  concept: {
    bg: "bg-green-50/60",
    border: "border-green-200",
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
    icon: Lightbulb,
    label: "Concept",
  },
  context_bridge: {
    bg: "bg-purple-50/60",
    border: "border-purple-200",
    iconBg: "bg-purple-100",
    iconColor: "text-purple-600",
    icon: LinkIcon,
    label: "Context Bridge",
  },
};

const defaultCardStyle: CardTypeStyle = {
  bg: "bg-gray-50/60",
  border: "border-gray-200",
  iconBg: "bg-gray-100",
  iconColor: "text-gray-600",
  icon: HelpCircle,
  label: "Card",
};

function extractContentText(content: CardData["content"]): string {
  if (content === null || content === undefined) return "";
  if (typeof content === "string") return content;
  if (typeof content === "object") {
    if (typeof content.text === "string") return content.text;
    if (typeof content.summary === "string") return content.summary;
    try {
      return JSON.stringify(content, null, 2);
    } catch {
      return "[Unable to display content]";
    }
  }
  return String(content);
}

function MarkdownContent({ content }: { content: string }) {
  return (
    <div className="prose-card">
      <ReactMarkdown>{content}</ReactMarkdown>
    </div>
  );
}

export default function SessionCard({ card }: CardProps) {
  const [expanded, setExpanded] = useState(false);

  const config = cardTypeConfig[card.card_type] || defaultCardStyle;
  const Icon = config.icon;
  const rawContent = extractContentText(card.content);
  const isLong = rawContent.length > PREVIEW_CHAR_LIMIT;
  const displayTitle = card.title?.trim() || "Untitled";

  const visibleContent = expanded
    ? rawContent
    : isLong
      ? (() => {
          const sliced = rawContent.slice(0, PREVIEW_CHAR_LIMIT);
          const lastSpace = sliced.lastIndexOf(" ");
          return (lastSpace > 0 ? sliced.slice(0, lastSpace) : sliced) + "...";
        })()
      : rawContent;

  return (
    <article
      className={`rounded-2xl border p-4 ${config.bg} ${config.border}`}
      aria-label={`${config.label} card: ${displayTitle}`}
    >
      {/* Card type badge + icon */}
      <div className="mb-3 flex items-center gap-2">
        <div
          className={`flex h-7 w-7 items-center justify-center rounded-lg ${config.iconBg}`}
          aria-hidden="true"
        >
          <Icon size={14} className={config.iconColor} />
        </div>
        <span className={`text-xs font-medium ${config.iconColor}`}>
          {config.label}
        </span>
        <span className="ml-auto flex items-center gap-1 rounded-full bg-gray-100 px-1.5 py-0.5 text-[10px] font-medium text-gray-500" title="This content was generated by AI based on your uploaded documents">
          <Sparkles size={10} />
          AI
        </span>
      </div>

      {/* Title */}
      <h3
        className="mb-1.5 text-sm font-semibold"
        style={{ color: "var(--ink)" }}
      >
        {displayTitle}
      </h3>

      {/* Content with markdown rendering */}
      {visibleContent ? (
        <>
          <div className="text-xs leading-relaxed text-gray-700">
            <MarkdownContent content={visibleContent} />
          </div>
          {isLong && (
            <button
              type="button"
              onClick={() => setExpanded((prev) => !prev)}
              className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-gray-500 transition-colors hover:text-gray-700"
              aria-expanded={expanded}
              aria-label={expanded ? "Show less content" : "Show more content"}
            >
              {expanded ? (
                <>
                  <ChevronUp size={12} aria-hidden="true" />
                  Show less
                </>
              ) : (
                <>
                  <ChevronDown size={12} aria-hidden="true" />
                  Show more
                </>
              )}
            </button>
          )}
        </>
      ) : (
        <p className="text-xs italic text-gray-400">No content</p>
      )}
    </article>
  );
}
